version: 2
jobs:
  build:
    working_directory: ~/karmaAutomation
    
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      
    steps:

      - checkout:
          path: ~/karmaAutomation

      - restore_cache:
          key: karmaAutomation-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: karmaAutomation-{{ checksum "pom.xml" }}
      
      - run: mvn test
